### ISSUE TITLE
What is printer name?

### ISSUE THREAD

**Issue by omidtaghavi1990** [DAmesberger/BrotherPrintServer#1]
I have set up a printer server and when I'm sending the request to the API, the API always prints on one of the printers regardless of what I sent as the printer name.
Right now I'm sending the name of all printers listed in the response of /api/printers, and all of them are getting printed through the same printer. It looks like it doesn't care about my input. Even if I send some random text as printer or if I don't send anything as the printer value the API still prints it on the same one.
Does the API work with multiple printers?

**Comment by DAmesberger** [comment]
I have never tried it with multiple printers and I currently don't have two printers to test it. Honestly this project was just quickly thrown together for a label printer browser plugin. The line that should set the printer is 
```
doc.SetPrinter(printData.printer, false);
```
in `Brother.cs`
It does return a boolean, but I just checked and it helpfully always return true.

I moved the `SetPrinter()` to run after `Open()`, so maybe that helps. If you want to try it pull the latest commit.
Also I read out the current printer name, if I provide a wrong name, even though `SetPrinter()` returns true, the GetPrinterName() function returns the last valid printer I used with `SetPrinter()`.
So you can try to set a Breakpoint at line 422 in Brother.cs and see what `printerName` is set to.

**Comment by omidtaghavi1990** [comment]
I think setting the last valid printer is the issue. But do you have any idea why it assumes that we provided the wrong printer name?

**Comment by DAmesberger** [comment]
Maybe the printer you are trying to use is not supported by the Brother b-PAC SDK. Is it a Brother label printer, and which type is it exactly?

**Comment by omidtaghavi1990** [comment]
Both of the printers are the same model and both of them are printing. But when I have them in my network as printer, it just prints on the first one no matter what I send as printer name.

**Comment by DAmesberger** [comment]
Ah, ok, can you post the content of the `api/printers` call? Are the two printers returned with the same name?
If it is the same you could try and specify the printer name in your `Devices and Printers` dialog. If two of the same exist it should create one with `(Copy 1)` at the end according to this document: 
https://support.brother.com/g/b/faqend.aspx?c=us&lang=en&prod=sc2000eus&faqid=faqp00001488_000

**Comment by omidtaghavi1990** [comment]
It got fixed. Thanks.

**Comment by omidtaghavi1990** [comment]
It got fixed, thanks.
