### ISSUE TITLE
When using multiple printers if always prints to the first one installed.

### ISSUE THREAD

**Issue by claytonsmithnz** [DAmesberger/BrotherPrintServer#2]
Hi,
Great little project, I am testing it, hoping to use it in a PowerApp.
We have a print server with multiple Brother printers install, when I try and print to a specified printer it always seems to print to the first Brother printer that was installed (possible default).
Also have you considered putting the URL/port number into the web.config file, so that it could easily be changed?

Thanks
Clayton

**Comment by claytonsmithnz** [comment]
Looks like you latest changes might have fixed this.

**Comment by okay-scam** [comment]
@DAmesberger Would it be possible for you to compile this version with the fix and publish it? I've tried to compile my self but no luck as I'm not familiar with C#.
